# action.yml
name: 'Node-RED Scorecard'
description: 'Run the scorecard tests'
inputs:
  package:  # id of input
    description: 'name of npm pacakge to test'
    required: true
    default: 'World'
outputs:
  scorecard: # id of output
    description: 'The scorecard.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}